<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bookings = [
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_1',
                'total_amount'              => 1000,
                'booking_date'              => '2025-01-01 10:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_2',
                'total_amount'              => 1000,
                'booking_date'              => '2025-01-02 13:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_3',
                'total_amount'              => 1000,
                'booking_date'              => '2025-01-05 16:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_4',
                'total_amount'              => 1000,
                'booking_date'              => '2025-01-15 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_5',
                'total_amount'              => 1000,
                'booking_date'              => '2025-01-25 22:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_6',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-02 10:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_7',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-08 13:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_8',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-10 16:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_9',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-11 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_10',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-13 22:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_11',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-14 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_12',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-15 15:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_13',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-20 18:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_14',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-21 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_15',
                'total_amount'              => 1000,
                'booking_date'              => '2025-02-28 13:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_16',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-01 16:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_17',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-01 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_18',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-02 22:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_19',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-03 18:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_20',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-03 19:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_21',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-04 20:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_22',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-04 21:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_23',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-10 20:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_24',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-12 16:00:00',
                'status'                    => 'Confirmed',
            ],
            [
                'user_id'                   => 1,
                'guest_email'               => null,
                'payment_method_id'         => 1,
                'qr_code'                   => 'qr_code_25',
                'total_amount'              => 1000,
                'booking_date'              => '2025-03-12 18:00:00',
                'status'                    => 'Confirmed',
            ],
        ];

        foreach ($bookings as $booking) {
            \App\Models\Booking::create($booking);
        }
    }
}
