<?php

namespace App\Enums;

enum PermissionEnum: string
{
    // General Permissions
    case VIEW_DASHBOARD = 'VIEW DASHBOARD';

    // Language Permissions
    case VIEW_ANY_LANGUAGES = 'VIEW ANY LANGUAGES';
    case VIEW_LANGUAGE = 'VIEW LANGUAGE';
    case CREATE_LANGUAGE = 'CREATE LANGUAGE';
    case UPDATE_LANGUAGE = 'UPDATE LANGUAGE';
    case DELETE_LANGUAGE = 'DELETE LANGUAGE';
    case RESTORE_LANGUAGE = 'RESTORE LANGUAGE';
    case FORCE_DELETE_LANGUAGE = 'FORCE DELETE LANGUAGE';

    // Classification Permissions
    case VIEW_ANY_CLASSIFICATIONS = 'VIEW ANY CLASSIFICATIONS';
    case VIEW_CLASSIFICATION = 'VIEW CLASSIFICATION';
    case CREATE_CLASSIFICATION = 'CREATE CLASSIFICATION';
    case UPDATE_CLASSIFICATION = 'UPDATE CLASSIFICATION';
    case DELETE_CLASSIFICATION = 'DELETE CLASSIFICATION';
    case IMPORT_CLASSIFICATION = 'IMPORT CLASSIFICATION';
    case EXPORT_CLASSIFICATION = 'EXPORT CLASSIFICATION';
    case RESTORE_CLASSIFICATION = 'RESTORE CLASSIFICATION';
    case FORCE_DELETE_CLASSIFICATION = 'FORCE DELETE CLASSIFICATION';

    // Country Permissions
    case VIEW_ANY_COUNTRIES     = 'VIEW ANY COUNTRIES';
    case VIEW_COUNTRY           = 'VIEW COUNTRY';
    case CREATE_COUNTRY         = 'CREATE COUNTRY';
    case UPDATE_COUNTRY         = 'UPDATE COUNTRY';
    case DELETE_COUNTRY         = 'DELETE COUNTRY';
    case IMPORT_COUNTRY         = 'IMPORT COUNTRY';
    case EXPORT_COUNTRY         = 'EXPORT COUNTRY';
    case RESTORE_COUNTRY        = 'RESTORE COUNTRY';
    case FORCE_DELETE_COUNTRY   = 'FORCE DELETE COUNTRY';
}
