<?php

namespace App\Enums;

enum PermissionEnum: string
{
    // General Permissions
    case VIEW_DASHBOARD = 'VIEW DASHBOARD';

    // Language Permissions
    case VIEW_ANY_LANGUAGES = 'VIEW ANY LANGUAGES';
    case VIEW_LANGUAGE = 'VIEW LANGUAGE';
    case CREATE_LANGUAGE = 'CREATE LANGUAGE';
    case UPDATE_LANGUAGE = 'UPDATE LANGUAGE';
    case DELETE_LANGUAGE = 'DELETE LANGUAGE';
    case RESTORE_LANGUAGE = 'RESTORE LANGUAGE';
    case FORCE_DELETE_LANGUAGE = 'FORCE DELETE LANGUAGE';

    // Classification Permissions
    case VIEW_ANY_CLASSIFICATIONS = 'VIEW ANY CLASSIFICATIONS';
    case VIEW_CLASSIFICATION = 'VIEW CLASSIFICATION';
    case CREATE_CLASSIFICATION = 'CREATE CLASSIFICATION';
    case UPDATE_CLASSIFICATION = 'UPDATE CLASSIFICATION';
    case DELETE_CLASSIFICATION = 'DELETE CLASSIFICATION';
    case IMPORT_CLASSIFICATION = 'IMPORT CLASSIFICATION';
    case EXPORT_CLASSIFICATION = 'EXPORT CLASSIFICATION';
    case RESTORE_CLASSIFICATION = 'RESTORE CLASSIFICATION';
    case FORCE_DELETE_CLASSIFICATION = 'FORCE DELETE CLASSIFICATION';

    // Movie Permissions
    case VIEW_ANY_MOVIES = 'VIEW ANY MOVIES';
    case VIEW_MOVIE = 'VIEW MOVIE';
    case CREATE_MOVIE = 'CREATE MOVIE';
    case UPDATE_MOVIE = 'UPDATE MOVIE';
    case DELETE_MOVIE = 'DELETE MOVIE';
    case IMPORT_MOVIE = 'IMPORT MOVIE';
    case EXPORT_MOVIE = 'EXPORT MOVIE';
    case RESTORE_MOVIE = 'RESTORE MOVIE';
    case FORCE_DELETE_MOVIE = 'FORCE DELETE MOVIE';

    // Country Permissions
    case VIEW_ANY_COUNTRIES     = 'VIEW ANY COUNTRIES';
    case VIEW_COUNTRY           = 'VIEW COUNTRY';
    case CREATE_COUNTRY         = 'CREATE COUNTRY';
    case UPDATE_COUNTRY         = 'UPDATE COUNTRY';
    case DELETE_COUNTRY         = 'DELETE COUNTRY';
    case IMPORT_COUNTRY         = 'IMPORT COUNTRY';
    case EXPORT_COUNTRY         = 'EXPORT COUNTRY';
    case RESTORE_COUNTRY        = 'RESTORE COUNTRY';
    case FORCE_DELETE_COUNTRY   = 'FORCE DELETE COUNTRY';

     // HallType Permissions
     case VIEW_ANY_HALL_TYPES    = 'VIEW ANY HALL TYPES';
     case VIEW_HALL_TYPE         = 'VIEW HALL TYPE';
     case CREATE_HALL_TYPE         = 'CREATE HALL TYPE';
     case UPDATE_HALL_TYPE         = 'UPDATE HALL TYPE';
     case DELETE_HALL_TYPE         = 'DELETE HALL TYPE';
     case IMPORT_HALL_TYPE         = 'IMPORT HALL TYPE';
     case EXPORT_HALL_TYPE         = 'EXPORT HALL TYPE';
     case RESTORE_HALL_TYPE        = 'RESTORE HALL TYPE';
     case FORCE_DELETE_HALL_TYPE  = 'FORCE DELETE HALL TYPE';

    // ScreenType Permissions
    case VIEW_ANY_SCREEN_TYPES    = 'VIEW ANY SCREEN TYPES';
    case VIEW_SCREEN_TYPE         = 'VIEW SCREEN TYPE';
    case CREATE_SCREEN_TYPE         = 'CREATE SCREEN TYPE';
    case UPDATE_SCREEN_TYPE         = 'UPDATE SCREEN TYPE';
    case DELETE_SCREEN_TYPE         = 'DELETE SCREEN TYPE';
    case IMPORT_SCREEN_TYPE         = 'IMPORT SCREEN TYPE';
    case EXPORT_SCREEN_TYPE         = 'EXPORT SCREEN TYPE';
    case RESTORE_SCREEN_TYPE        = 'RESTORE SCREEN TYPE';
    case FORCE_DELETE_SCREEN_TYPE  = 'FORCE DELETE SCREEN TYPE';

     // Genre Permissions
     case VIEW_ANY_GENRES = 'VIEW ANY GENRES';
     case VIEW_GENRE = 'VIEW GENRE';
     case CREATE_GENRE = 'CREATE GENRE';
     case UPDATE_GENRE = 'UPDATE GENRE';
     case DELETE_GENRE = 'DELETE GENRE';
     case IMPORT_GENRE = 'IMPORT GENRE';
     case EXPORT_GENRE = 'EXPORT GENRE';
     case RESTORE_GENRE = 'RESTORE GENRE';
     case FORCE_DELETE_GENRE = 'FORCE DELETE GENRE';

     // Hall Permissions
    case VIEW_ANY_HALLS = 'VIEW ANY HALLS';
    case VIEW_HALL = 'VIEW HALL';
    case CREATE_HALL = 'CREATE HALL';
    case UPDATE_HALL = 'UPDATE HALL';
    case DELETE_HALL = 'DELETE HALL';
    case IMPORT_HALL = 'IMPORT HALL';
    case EXPORT_HALL = 'EXPORT HALL';
    case RESTORE_HALL = 'RESTORE HALL';
    case FORCE_DELETE_HALL = 'FORCE DELETE HALL';

    // SeatType Permissions
    case VIEW_ANY_SEAT_TYPES = 'VIEW ANY SEAT TYPES';
    case VIEW_SEAT_TYPE = 'VIEW SEAT TYPE';
    case CREATE_SEAT_TYPE = 'CREATE SEAT TYPE';
    case UPDATE_SEAT_TYPE = 'UPDATE SEAT TYPE';
    case DELETE_SEAT_TYPE = 'DELETE SEAT TYPE';
    case IMPORT_SEAT_TYPE = 'IMPORT SEAT TYPE';
    case EXPORT_SEAT_TYPE = 'EXPORT SEAT TYPE';
    case RESTORE_SEAT_TYPE = 'RESTORE SEAT TYPE';
    case FORCE_DELETE_SEAT_TYPE = 'FORCE DELETE SEAT TYPE';

    // Show Permissions
    case VIEW_ANY_SHOWS = 'VIEW ANY SHOWS';
    case VIEW_SHOW = 'VIEW SHOW';
    case CREATE_SHOW = 'CREATE SHOW';
    case UPDATE_SHOW = 'UPDATE SHOW';
    case DELETE_SHOW = 'DELETE SHOW';
    case IMPORT_SHOW = 'IMPORT SHOW';
    case EXPORT_SHOW = 'EXPORT SHOW';
    case RESTORE_SHOW = 'RESTORE SHOW';
    case FORCE_DELETE_SHOW = 'FORCE DELETE SHOW';
}
